name: metrono_master
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  theme_provider: ^0.6.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  country_flags: ^2.2.0
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/sounds/
